### ISSUE TITLE
select which T1 to use when multiple _T1w.nii.gz are present

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/smriprep#104]
For instance if you acquire in the same session a brain T1w which outputs `..._T1w.nii.gz` and `..._rec-norm_T1w.nii.gz` (scanner normalization) and also a cervical spinal cord T1w named `....loc-spine_T1w.nii.gz`, fmriprep seems to try making an average of all these. 
Is there an option to select from a BIDS anat directory, the specific T1w to select for anatomical processing using a glob or else?
Thanks!

**Comment by bpinsard** [comment]
Ok thanks!
I guess it would be useful to have options --anat_bids_filter and --func_bids_filter to pass to pybids in fmriprep and smriprep, and maybe deprecate the -T option.

**Comment by oesteban** [comment]
Related - #31

**Comment by Park-Patrick** [comment]
Also interested in this issue! i.e. where there are multiple versions of the same T1w scan due to different gradient correction methods applied.

Happy to help as well. In our case, the file names look like 
`sub-xx_acq-yy_rec-DIS3D_run-01_T1w`
`sub-xx_acq-yy_rec-DIS2D_run-01_T1w`
so maybe just parsing for the tag and adding a command line argument `--t1w_select` to specify?

**Comment by utooley** [comment]
I've been watching the issues/PRs about this since asking about it on [Neurostars](https://neurostars.org/t/replicable-scripts-bids-and-curating-data/2623) a long time ago, and was currently going to stick with simply adding the anatomicals that I don't want to use to the `.bidsignore` (as opposed to removing them entirely), in line with the suggestion by @emdupre on the fmriprep PR. I think this will work generally (but haven't tested it yet), but if this feature is close to being implemented in a new release, I might wait on the trouble of doing that... Any updates?

**Comment by effigies** [comment]
Adding things to `.bidsignore` only affects the validator, not pybids or fMRIPrep.

I think the selection PRs are nearly there... I can try to have a look this week.

**Comment by emdupre** [comment]
> Adding things to .bidsignore only affects the validator, not pybids or fMRIPrep.

Sorry @effigies: Is that an expected situation ? I didn't think so based on discussion in https://github.com/bids-standard/bids-specification/issues/131 and https://github.com/bids-standard/pybids/issues/378. Or is this something particular to *MRIPrep ?

**Comment by effigies** [comment]
It's what I expect... I can read through those threads to see if there was an alternative consensus, though. Not likely to be tonight.

**Comment by effigies** [comment]
There doesn't seem to be a clear consensus that came out, but I can't pin down a population vector of any magnitude.

I think one problem we'll face in fMRIPrep is that "ignore" is a blunt instrument and it's encoded in the dataset, not in the execution inputs. I may have two perfectly BIDS-valid T1w images but only want to pass one to fMRIPrep. `.bidsignore` feels like the wrong way to handle that. Second, `ignore` in the BIDS-validator context means "do not error on", but in pybids it sounds like we want it to mean "do not index". BUT, we use BIDSValidator errors to mean "do not index", so suppressing errors might intuitively mean "index in spite of errors".

The conceptual ambiguity is probably part of why we haven't moved toward making `.bidsignore` official for anything but bids-validator. And I think this input form is much more clear. I will see if we can push on this and aim for inclusion in fMRIPrep 20.1.

**Comment by oesteban** [comment]
Has the ``--bids-filters`` flag resolved this issue indirectly?

**Comment by bpinsard** [comment]
yes!
