### ISSUE TITLE
T1w brain mask too liberal

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/smriprep#23]
![image](https://user-images.githubusercontent.com/238759/36927506-d923da2a-1e32-11e8-895d-759d1ddf681e.png)
ds000051/reportlets/fmriprep/sub-02/anat/sub-02_T1w_seg_brainmask.svg

Seems that in this case the refinement heuristic makes the mask worse. Below is the surface reconstruction plot
![image](https://user-images.githubusercontent.com/238759/36927484-bfa7ebc2-1e32-11e8-94fa-cc8dc0699de7.png)
`ds000051/reportlets/fmriprep/sub-02/anat/sub-02_T1w_reconall.svg`

**Comment by oesteban** [comment]
We still see some errors (e.g., ds000114/sub-02) but this seems to have improved a lot. ds000114/sub-{03,04} and ds000051/sub-02 look much better (actually, pretty good).

<img width="934" alt="Screen Shot 2019-10-16 at 7 05 38 PM" src="https://user-images.githubusercontent.com/598470/66972043-1dd01b00-f048-11e9-9555-a6594be96cbe.png">

I have started a wiki for very hard cases for brain extraction (https://github.com/poldracklab/smriprep/wiki/Brain-Extraction-from-T1w---very-hard-cases) and opened the list with ds000114/sub-02.

Since the underlying issue seems resolved, I'll leave the improvement of brain extraction to that list when we decide to change the procedure or find a better tool.
