### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by oesteban** [poldracklab/smriprep#46]
Set up a documentation build. Possibly pushing to github pages directly from Circle. WDYT?

**Comment by rwblair** [comment]
https://robpol86.github.io/sphinxcontrib-versioning/

**Comment by jdkent** [comment]
Last year, I tried configuring [doctr](https://drdoctr.github.io/) with sphinxcontrib-versioning, but that repository was essentially abandoned and I was trying to get forks of that project to work with newer versions of sphinx. I went back to readthedocs with my tail between my legs since it was the simplest "out of the box" solution. However, looks like sphinxcontrib-versioning may be [gaining new maintainers](https://github.com/Robpol86/sphinxcontrib-versioning/issues/59#issuecomment-459949332) and may be a viable solution (not that it was a non-viable solution when I tried, I just didn't want to invest the time to figure it out when readthedocs already worked).
