### ISSUE TITLE
Custom (study specific) templates

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/smriprep#8]
Custom (volume and surface) templates derived from a particular dataset have been shown to improve overlap between participants. It is also the recommended way to deal with smaller head sizes in developmental populations. Both ANTs and FreeSurfer support building such templates.

**Comment by jflournoy** [comment]
I want to make sure I'm reading this thread correctly, since both Klein et al (2010) and Ghosh et al (2010) indicate that registration using (e.g., ANTS +) custom templates should improve registration. Is it the case that after another decade of experience, you, @satra, have found that as long as the sample is large enough and participants are older than 4 years, one might as well just register directly MNI152NLin2009cAsym? I wonder if somewhere out there is a paper being written to support this, since we are currently using Ghosh et al 2010 to justify using the custom template approach. Thanks for the discussion here.

**Comment by satra** [comment]
@jflournoy - the conversation has become even more complicated i would say. anatomical registration is just one part of the story. now you have multimodal registration via MSMAll, [Diffusion Map embedding alignment](https://www.ncbi.nlm.nih.gov/pubmed/26855977), and [epi-T1-based surface registration](https://www.ncbi.nlm.nih.gov/pubmed/27079529).

at the end of the day, i would say the decision should be based on what you are doing registration for, and how you may consider validating the registration.

if you are able to tune parameters, i think any registration tool can give you good registration. perhaps one way to validate, not fully adequate is to run freesurfer on your template, and just as we did in klein et al, evaluate how well the template aparc areas overlap with your individuals registered to template. this is not perfect, but may be give you a good idea of registration errors and locations.

sorry there are two many parameters to the puzzle, so an answer is not straightforward.

**Comment by oesteban** [comment]
Using custom templates is now possible via TemplateFlow. Because this thread is very valuable, I have referenced it from [TemplateFlow's documentation](https://www.templateflow.org/client/#custom-study-population-specific-templates)
